# Generated by Django 5.2.8 on 2026-05-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_force_phone_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weather_access',
            field=models.BooleanField(default=True),
        ),
    ]
