import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAgriLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('season', models.CharField(blank=True, max_length=30)),
                ('avg_temp', models.FloatField(blank=True, null=True)),
                ('avg_moisture', models.FloatField(blank=True, null=True)),
                ('total_rain_mm', models.FloatField(default=0.0)),
                ('water_used_l', models.FloatField(default=0.0)),
                ('rain_prob', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agri_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('secret_key', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=150)),
                ('pairing_code', models.CharField(max_length=20, unique=True)),
                ('activation_token', models.CharField(blank=True, max_length=50)),
                ('is_paired', models.BooleanField(default=False)),
                ('crop_type', models.CharField(blank=True, max_length=100)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('wifi_ssid', models.CharField(blank=True, default='', max_length=64)),
                ('wifi_password', models.CharField(blank=True, default='', max_length=64)),
                ('wifi_pending', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(blank=True, choices=[('Sandy', 'Sandy'), ('Clay', 'Clay'), ('Silt', 'Silt'), ('Loam', 'Loam'), ('Sandy Loam', 'Sandy Loam'), ('Clay Loam', 'Clay Loam'), ('Peat', 'Peat'), ('Chalk', 'Chalk')], max_length=50)),
                ('plant_type', models.CharField(blank=True, max_length=100)),
                ('moisture_min', models.FloatField(default=40.0)),
                ('moisture_max', models.FloatField(default=70.0)),
                ('moisture_critical_low', models.FloatField(default=20.0)),
                ('irrigation_duration', models.PositiveIntegerField(default=30, help_text='Minutes per irrigation cycle')),
                ('notes', models.TextField(blank=True)),
                ('weather_lat', models.FloatField(blank=True, null=True)),
                ('weather_lon', models.FloatField(blank=True, null=True)),
                ('weather_location_name', models.CharField(blank=True, default='', max_length=200)),
                ('admin_weather_lat', models.FloatField(blank=True, null=True)),
                ('admin_weather_lon', models.FloatField(blank=True, null=True)),
                ('admin_weather_location_name', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('kit_type', models.CharField(choices=[('basic', 'Basic Kit — UGX 700,000'), ('advanced', 'Advanced Kit — UGX 2,000,000')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_ugx', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='LocationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'verbose_name': 'Location Cache'},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pump', 'Pump'), ('weather', 'Weather'), ('water', 'Low Water'), ('sensor', 'Sensor Failure'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('device_name', models.CharField(blank=True, max_length=150)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='PlantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('water_demand_l_day', models.FloatField(default=5.5)),
                ('stress_temp_high', models.FloatField(default=32.0)),
                ('stress_moisture_low', models.FloatField(default=30.0)),
                ('root_depth_factor', models.FloatField(default=1.0)),
                ('season_adjust', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_builtin', models.BooleanField(default=False, help_text='True for seeded built-in profiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['label']},
        ),
        migrations.CreateModel(
            name='PumpCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_commands', to='api.device')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pump_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-issued_at']},
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('water_tank', models.FloatField(blank=True, null=True)),
                ('pump_status', models.CharField(default='Off', max_length=20)),
                ('irrig_cycles', models.PositiveIntegerField(default=0)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('gps_place', models.CharField(blank=True, default='', max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.device')),
            ],
            options={'ordering': ['-recorded_at']},
        ),
        migrations.CreateModel(
            name='SMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=False)),
                ('pump_alerts', models.BooleanField(default=True)),
                ('weather_alerts', models.BooleanField(default=True)),
                ('low_water_alerts', models.BooleanField(default=True)),
                ('sensor_failure_alerts', models.BooleanField(default=True)),
                ('phone_numbers', models.JSONField(default=list)),
                ('phones_dirty', models.BooleanField(default=True, help_text='True = hardware must re-fetch phone numbers')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'SMS Settings'},
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_online', models.BooleanField(default=True)),
                ('maintenance_title', models.CharField(default='System Maintenance', max_length=200)),
                ('maintenance_message', models.TextField(default='The system is currently under maintenance. Please check back later.')),
                ('maintenance_sub', models.CharField(blank=True, default='We apologize for the inconvenience.', max_length=300)),
                ('online_at', models.DateTimeField(blank=True, help_text='Scheduled time to go back online', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'System Settings'},
        ),
        migrations.CreateModel(
            name='WeatherAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(default='weather', max_length=50)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('success', models.BooleanField(default=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-accessed_at']},
        ),
        migrations.AlterUniqueTogether(
            name='dailyagrilog',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='pumpcommand',
            index=models.Index(fields=['device', '-issued_at'], name='pump_cmd_device_time_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', '-recorded_at'], name='device_recorded_at_idx'),
        ),
    ]
