# Generated by Django 6.0.5 on 2026-05-24 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(blank=True, choices=[('Sandy', 'Sandy'), ('Clay', 'Clay'), ('Silt', 'Silt'), ('Loam', 'Loam'), ('Sandy Loam', 'Sandy Loam'), ('Clay Loam', 'Clay Loam'), ('Peat', 'Peat'), ('Chalk', 'Chalk')], max_length=50)),
                ('plant_type', models.CharField(blank=True, max_length=100)),
                ('moisture_min', models.FloatField(default=40.0)),
                ('moisture_max', models.FloatField(default=70.0)),
                ('moisture_critical_low', models.FloatField(default=20.0)),
                ('irrigation_duration', models.PositiveIntegerField(default=30, help_text='Minutes per irrigation cycle')),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
