# Generated by Django 5.2.8 on 2026-05-28 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_weatheraccesslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_online', models.BooleanField(default=True)),
                ('maintenance_title', models.CharField(default='System Maintenance', max_length=200)),
                ('maintenance_message', models.TextField(default='The system is currently under maintenance. Please check back later.')),
                ('maintenance_sub', models.CharField(blank=True, default='We apologize for the inconvenience.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
