# Generated by Django 5.2.8 on 2026-05-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='online_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled time to go back online', null=True),
        ),
    ]
