# Generated by Django 5.2.8 on 2026-05-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_farmsettings_weather_location'),
        ('api', '0009_dailyagrilog'),
    ]

    operations = [
    ]
