# Generated by Django 5.2.8 on 2026-05-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_location_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsettings',
            name='admin_weather_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmsettings',
            name='admin_weather_location_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='farmsettings',
            name='admin_weather_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
