# Generated by Django 5.2.8 on 2026-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pumpcommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('water_demand_l_day', models.FloatField(default=5.5)),
                ('stress_temp_high', models.FloatField(default=32.0)),
                ('stress_moisture_low', models.FloatField(default=30.0)),
                ('root_depth_factor', models.FloatField(default=1.0)),
                ('season_adjust', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_builtin', models.BooleanField(default=False, help_text='True for seeded built-in profiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
