# Generated by Django 5.2.8 on 2026-06-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_smssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssettings',
            name='phones_dirty',
            field=models.BooleanField(default=True, help_text='True = hardware must re-fetch phone numbers'),
        ),
    ]
