from django.urls import path
from .views import (
    GPSFallbackView, DeviceSettingsView, DeviceActivateView,
    DeviceListView, DeviceDetailView, ConnectDeviceView,
    DashboardView, HealthCheckView, WeatherView, WeatherLocationView, LocationSearchView,
    NotificationListView, NotificationDetailView, NotificationMarkAllReadView,
    NotificationUnreadCountView,
    WifiStatusView, WifiScanView, WifiConfigureView, WifiCredentialsFetchView,
    FarmSettingsView, PairDeviceView, TestDeviceView,
    SensorIngestView, LiveDataView, PumpControlView, PumpCommandPollView, IntelligenceView,
    PlantProfilesView, SMSSettingsView,
    VapidKeyView, PushSubscribeView, PushUnsubscribeView, BadgeView, TestPushView,
    HardwareOrderView, HardwareOrderListView, HardwareOrderDetailView,
)

urlpatterns = [
    path('core/health/',                   HealthCheckView.as_view(),              name='health-check'),
    path('dashboard/',                     DashboardView.as_view(),                name='dashboard'),
    path('weather/',                       WeatherView.as_view(),                  name='weather'),
    path('weather/location/',              WeatherLocationView.as_view(),          name='weather-location'),
    path('devices/',                       DeviceListView.as_view(),               name='device-list'),
    path('devices/<int:pk>/',              DeviceDetailView.as_view(),             name='device-detail'),
    path('device/connect/',                ConnectDeviceView.as_view(),            name='device-connect'),
    path('device/pair/',                   PairDeviceView.as_view(),               name='device-pair'),
    path('device/test/',                   TestDeviceView.as_view(),               name='device-test'),
    path('sensor/ingest/',                 SensorIngestView.as_view(),             name='sensor-ingest'),
    path('live-data/',                     LiveDataView.as_view(),                 name='live-data'),
    path('pump/control/',                  PumpControlView.as_view(),              name='pump-control'),
    path('pump/poll/',                     PumpCommandPollView.as_view(),          name='pump-poll'),
    path('notifications/',                 NotificationListView.as_view(),         name='notification-list'),
    path('notifications/unread-count/',    NotificationUnreadCountView.as_view(),  name='notification-unread-count'),
    path('notifications/mark-all-read/',   NotificationMarkAllReadView.as_view(),  name='notification-mark-all'),
    path('notifications/<int:pk>/',        NotificationDetailView.as_view(),       name='notification-detail'),
    path('notifications/vapid-key/',       VapidKeyView.as_view(),                 name='vapid-key'),
    path('notifications/subscribe/',       PushSubscribeView.as_view(),            name='push-subscribe'),
    path('notifications/unsubscribe/',     PushUnsubscribeView.as_view(),          name='push-unsubscribe'),
    path('notifications/badge/',           BadgeView.as_view(),                    name='badge'),
    path('notifications/test-push/',       TestPushView.as_view(),                 name='test-push'),
    path('wifi/status/',                   WifiStatusView.as_view(),               name='wifi-status'),
    path('wifi/scan/',                     WifiScanView.as_view(),                 name='wifi-scan'),
    path('wifi/configure/',                WifiConfigureView.as_view(),            name='wifi-configure'),
    path('wifi/credentials/',              WifiCredentialsFetchView.as_view(),     name='wifi-credentials'),
    path('intelligence/',                 IntelligenceView.as_view(),             name='intelligence'),
    path('location-search/',              LocationSearchView.as_view(),           name='location-search'),
    path('farm-settings/',                 FarmSettingsView.as_view(),             name='farm-settings'),
    path('sms-settings/',                  SMSSettingsView.as_view(),              name='sms-settings'),
    path('plant-profiles/',                PlantProfilesView.as_view(),            name='plant-profiles'),
    path('orders/hardware/',               HardwareOrderView.as_view(),            name='hardware-order'),
    path('orders/hardware/list/',          HardwareOrderListView.as_view(),        name='hardware-order-list'),
    path('orders/hardware/<int:pk>/',      HardwareOrderDetailView.as_view(),      name='hardware-order-detail'),

    path('device/settings/',               DeviceSettingsView.as_view(),           name='device-settings'),
    path('device/activate/',               DeviceActivateView.as_view(),           name='device-activate'),
    path('device/gps-fallback/',           GPSFallbackView.as_view(),              name='device-gps-fallback'),
]
